/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import pkgDatos.dbConexion;

/**
 *
 * @author kiritoxcii
 */
public class frmES extends javax.swing.JFrame {

    /**
     * Creates new form frmES
     */
    
    dbConexion con;
    
    public frmES() {
        initComponents();
        
        con = new dbConexion();
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        lblMarca = new javax.swing.JLabel();
        lblRam = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblBoard = new javax.swing.JLabel();
        lblProcesador = new javax.swing.JLabel();
        lblDiscoD = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtRam = new javax.swing.JTextField();
        txtBoard = new javax.swing.JTextField();
        txtProcesador = new javax.swing.JTextField();
        txtDiscoD = new javax.swing.JTextField();
        lblFuenteP = new javax.swing.JLabel();
        txtFuenteP = new javax.swing.JTextField();
        lblSintomas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlSintomas = new javax.swing.JList();
        lblDatosdelEquipo = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnAgregarEquipo = new javax.swing.JButton();
        jmbPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMarca.setText("Marca:");

        lblRam.setText("RAM:");

        lblModelo.setText("Modelo:");

        lblBoard.setText("Board:");

        lblProcesador.setText("Procesador:");

        lblDiscoD.setText("Disco Duro:");

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        txtRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRamActionPerformed(evt);
            }
        });

        txtBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoardActionPerformed(evt);
            }
        });

        txtProcesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcesadorActionPerformed(evt);
            }
        });

        txtDiscoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscoDActionPerformed(evt);
            }
        });

        lblFuenteP.setText("Fuente de Poder:");

        txtFuenteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuentePActionPerformed(evt);
            }
        });

        lblSintomas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSintomas.setText("SÍNTOMAS");

        jlSintomas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlSintomas);

        lblDatosdelEquipo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDatosdelEquipo.setText("DATOS DEL EQUIPO...");

        btnConsultar.setText("Consultar");

        btnAgregarEquipo.setText("Agregar");

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpPrincipalLayout.createSequentialGroup()
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPrincipalLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMarca)
                            .addComponent(lblModelo)
                            .addComponent(lblDiscoD)
                            .addComponent(lblProcesador)
                            .addComponent(lblBoard)
                            .addComponent(lblRam)
                            .addComponent(lblFuenteP))
                        .addGap(75, 75, 75)
                        .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFuenteP, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDiscoD, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jdpPrincipalLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnAgregarEquipo)
                        .addGap(155, 155, 155)
                        .addComponent(btnConsultar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSintomas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdpPrincipalLayout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(lblDatosdelEquipo)
                    .addContainerGap(845, Short.MAX_VALUE)))
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPrincipalLayout.createSequentialGroup()
                        .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(lblMarca))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpPrincipalLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblModelo)
                                .addGap(18, 18, 18)
                                .addComponent(lblRam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBoard)
                                .addGap(18, 18, 18)
                                .addComponent(lblProcesador)
                                .addGap(18, 18, 18)
                                .addComponent(lblDiscoD))
                            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiscoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFuenteP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFuenteP))))
                        .addGap(50, 50, 50)
                        .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultar)
                            .addComponent(btnAgregarEquipo)))
                    .addGroup(jdpPrincipalLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblSintomas)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 98, Short.MAX_VALUE))
            .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdpPrincipalLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(lblDatosdelEquipo)
                    .addContainerGap(462, Short.MAX_VALUE)))
        );
        jdpPrincipal.setLayer(lblMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lblRam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lblModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lblBoard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lblProcesador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lblDiscoD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(txtMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(txtModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(txtRam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(txtBoard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(txtProcesador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(txtDiscoD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lblFuenteP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(txtFuenteP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lblSintomas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lblDatosdelEquipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(btnConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(btnAgregarEquipo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("/");
        jmbPrincipal.add(jMenu1);

        jMenu2.setText("Edit");
        jmbPrincipal.add(jMenu2);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRamActionPerformed

    private void txtBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoardActionPerformed

    private void txtProcesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcesadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcesadorActionPerformed

    private void txtDiscoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscoDActionPerformed

    private void txtFuentePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuentePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuentePActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmES().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEquipo;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JList jlSintomas;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JLabel lblBoard;
    private javax.swing.JLabel lblDatosdelEquipo;
    private javax.swing.JLabel lblDiscoD;
    private javax.swing.JLabel lblFuenteP;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblProcesador;
    private javax.swing.JLabel lblRam;
    private javax.swing.JLabel lblSintomas;
    private javax.swing.JTextField txtBoard;
    private javax.swing.JTextField txtDiscoD;
    private javax.swing.JTextField txtFuenteP;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtProcesador;
    private javax.swing.JTextField txtRam;
    // End of variables declaration//GEN-END:variables
/*
    Agregar un internal frame a un desktop pane
    jdpPrimero.add(jifPrestamo);
         jifPrestamo.setSize(jifPrestamo.getPreferredSize());                
         try {
            jifPrestamo.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmSistemaCentroCultural.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    Metodo para validar contrasenia
    
     public boolean passwordCorrecta(char[] password, clsAdministrador admin) {
   boolean esCorrecta;
   if (password.length != admin.getPassword().length) {
       esCorrecta = false;
   } else {
       esCorrecta = Arrays.equals(password, admin.getPassword());
   }
   return esCorrecta;
}
    
    */
    
    
}
